### ISSUE TITLE
Add circular queue.

### ISSUE THREAD

**Issue by pracheesingh03** [pracheesingh03/openSourceContributions#1]
Algorithm of circular queue using C language

**Comment by abhi2000-bit** [comment]
[circular q.txt](https://github.com/pracheesingh03/openSourceContributions/files/5331336/circular.q.txt)

**Comment by pracheesingh03** [comment]
Add this file in the forked repository.
Then make a pull request. I will merge it.

**Comment by pracheesingh03** [comment]
> [circular q.txt](https://github.com/pracheesingh03/openSourceContributions/files/5331336/circular.q.txt)
Add this file in the forked repository.
Then make a pull request. I will merge it.
@abhi2000-bit
